### ISSUE TITLE
Make lamp data for graph and send to flutter app

### ISSUE THREAD

**Issue by personpal** [Pervasive-Computing/sumo-networks#2]
We want 24 hour format, with average light level every hour for each lamp

It should be possible to request data for a single lamp at a time

**Comment by personpal** [comment]
We want 24 hour format, with average light level every hour for each lamp

It should be possible to request data for a single lamp at a time

**Comment by kpbaks** [comment]
![Image](https://github.com/Pervasive-Computing/sumo-networks/assets/57013304/7e207ab3-726f-4540-929d-cef8d75faa52)


here is the request schema that the server expects
"reducer" can be one of: "mean", "median"
"per" can be one of: "hour", "day", "week"
